# Generated by Django 5.2.1 on 2025-11-10 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_alter_order_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_Item',
            new_name='OrderItem',
        ),
        migrations.RenameModel(
            old_name='Product_Image',
            new_name='ProductImage',
        ),
    ]
